sonar.projectKey=biblioteca-calidad
sonar.projectName=Biblioteca Calidad

sonar.sources=src
sonar.tests=tests

sonar.exclusions=**/node_modules/**,**/coverage/**
sonar.test.inclusions=tests/**/*.test.js

sonar.javascript.lcov.reportPaths=coverage/lcov.info
sonar.sourceEncoding=UTF-8